adega/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path(
        'address_manager/',
        include('address_manager.urls'),
        name='address_manager'
    ),
    path(
        'company_manager/',
        include('company_manager.urls'),
        name='company_manager'
    ),
    path(
        'person_manager/',
        include('person_manager.urls'),
        name='person_manager'
    ),
    path(
        'category_manager/',
        include('category_manager.urls'),
        name='category_manager'
    ),
    path(
        'warehouse_manager/',
        include('warehouse_manager.urls'),
        name='warehouse_manager'
    ),
    path(
        'item_manager/',
        include('item_manager.urls'),
        name='item_manager'
    ),
    path(
        'transaction_manager/',
        include('transaction_manager.urls'),
        name='transaction_manager'
    ),
    path(
        'report_manager/',
        include('report_manager.urls'),
        name='report_manager'
    ),

    path("select2/", include("django_select2.urls")),
]

home/urls.py
from . import views
from django.urls import path, include


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('help/about/', views.help_about, name='help_about'),
    path('help/entities/', views.help_entities, name='help_entities'),
    path('help/examples/', views.help_examples, name='help_examples'),
    path('login/', views.hlogin, name='hlogin'),
    path('logout/', views.hlogout, name='hlogout'),
    path(
        'change_password/',
        views.change_password,
        name='change_password'
    ),
]

report_manager/urls.py
from . import views
from django.urls import path

app_name = "report_manager"
urlpatterns = [
    path('list_by/<str:list_type>/', views.list_by, name='list_by'),
    path('list_by/api/<str:list_type>/', views.list_by_api, name='list_by_api'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
# forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import  Button, ButtonHolder, Layout, Submit
from django import forms
from django.contrib.auth.models import User


class ChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        label="Senha Antiga",
        widget=forms.PasswordInput(attrs={"placeholder": "Senha Antiga"})
    )
    new_password = forms.CharField(
        label="Nova Senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Nova Senha"})
    )
    confirm_password = forms.CharField(
        label="Confirmar Senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirmar Senha"})
    )

    class Meta:
        model = User
        fields = ["old_password", "new_password", "confirm_password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Crispy Forms Helper and Form Method
        self.helper = FormHelper()
        self.helper.form_method = "POST"

        # Define the layout of the form
        self.helper.layout = Layout(
            "old_password",
            "new_password",
            "confirm_password",
            ButtonHolder(
                Submit(
                    "submit",
                    "Alterar Senha",
                    css_class="btn btn-primary"),
                Button("cancel",
                        "Cancelar",
                        css_class="btn btn-secondary",
                        onclick="window.location.href='/'"),
                        css_class=("d-grid gap-2 d-md-flex "
                        "justify-content-end"),
            )
        )


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        label="Usuário",
        widget=forms.TextInput(attrs={"placeholder": "Usuário"})
    )
    password = forms.CharField(
        label="Senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Senha"})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # Set the form tag attributes
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"

        # Set the layout of the form
        self.helper.layout.append(
            Submit("submit", "Login", css_class="w-100 mt-4"),
        )

home/views.py
from .forms import LoginForm
from .forms import ChangePasswordForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_not_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse

def change_password(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.POST or None)
        if form.is_valid():
            old_password = form.cleaned_data.get("old_password")
            new_password = form.cleaned_data.get("new_password")
            confirm_password = form.cleaned_data.get("confirm_password")

            if new_password != confirm_password:
                messages.error(request, "As senhas não coincidem.")
                return redirect(reverse('home:change_password'))

            user = authenticate(
                request,
                username=request.user.username,
                password=old_password
            )
            if user is not None:
                user.set_password(new_password)
                user.save()
                messages.success(request, "Senha alterada com sucesso.")
                return redirect(reverse('home:index'))
            else:
                messages.error(request, "Senha antiga inválida.")
                return redirect(reverse('home:change_password'))
    else:
        form = ChangePasswordForm()
    return render(
        request,
        'home/change_password.html',
        {'form': form, 'action': 'Alterar Senha'}
    )

def help_about(request):
        return render(request, 'home/help_about.html')

def help_entities(request):
        return render(request, 'home/help_entities.html')

def help_examples(request):
        return render(request, 'home/help_examples.html')

@login_not_required
def index(request):
    if request.user.is_authenticated:
        return render(request, 'home/home.html')
    else:
        return redirect(reverse('home:hlogin'))

@login_not_required
def hlogin(request):
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("home:index"))
            else:
                form.add_error(None, "Usuário ou senha inválidos.")
    return render(request, "home/login.html", {"form": form})

@login_not_required
def hlogout(request):
    if request.user.is_authenticated:
        logout(request)
        # successfully logged out message
        messages.success(request, "Você fez o logout com sucesso.")
    else:
        messages.warning(request, "Você não está logado.")
    return redirect("home:hlogin")

home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Adega</title>
    <link rel="icon" type="image/png" href="{% static 'home/images/adega_favicon.png' %}">

    <!-- Bootstrap styles and icons-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">

    <!-- DataTables styles -->
    <link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.2/sl-3.0.0/datatables.min.css" rel="stylesheet" integrity="sha384-MZTUU4w9Rnab6WfsYBXofDEVX/irP8L6cA3Qh+28BCClZ8EONTHdhe4US4hGmVst" crossorigin="anonymous">

    <!-- Select 2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <!-- Adega styles -->
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">

    {% block additional_style %}
    {% endblock %}
  </head>
  <body style="padding-top: 0rem;">
    <!-- Bootstrap scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <!-- DataTables/jQuery scripts -->
    <script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.2/sl-3.0.0/datatables.min.js" integrity="sha384-tvO3HisKISiIElG0LJEDUnwmU962Mufd53UK9x6JdflxK0lFDS+EANzfQqBgp/kd" crossorigin="anonymous"></script>

    <!-- jQuery mask-->
    <script src="https://cdn.jsdelivr.net/npm/jquery-mask-plugin@1.14.16/dist/jquery.mask.min.js"></script>

    <!-- Select 2 -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <!-- adega scripts -->
    <script src="{% static 'home/scripts/responsive_theme.js' %}"></script>
      {% block body %}
      {% endblock %}
  </body>
</html>

home/templates/home/change_password.html
{% extends "home/menu.html" %}
{% block content %}
  <div class="container d-flex justify-content-center">
    <div class="card bg-body-tertiary shadow" style="width: 36rem;">
      <div class="container" style="padding: 2rem;">
        {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div class="alert alert-success mt-3" role="alert">
              <b>Sucesso: </b>{{ message }}
            </div>
          {% endif %}
          {% if message.tags == 'error' %}
            <div class="alert alert-danger mt-3" role="alert">
              <b>Erro: </b>{{ message }}
            </div>
          {% endif %}
          {% endfor %}
        {% endif %}
      <h3 style="margin-bottom: 2rem;">{{ action }}</h3>
      <form method="post" novalidate>
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {% crispy form %}
      </form>
    </div>
    </div>
  </div>
  <script>
    // - Change here ---------------------------------------------------------
    $(document).ready(function () {
      $('#id_name').focus();
    });
    // -----------------------------------------------------------------------
  </script>
{% endblock %}

home/templates/home/help.html
{% extends 'home/menu.html' %}
{% load static %}
{% block content %}
  <!-- Section  -->
  <h1>Ajuda</h1>

  <!-- Greetings -->
  <h4 style="font-style: italic;">
    Olá{% if user.first_name %}, {{ user.first_name }} {{ user.last_name }}{% endif %}!
  </h4>

  <!-- Text -->
  <p>
    A <code>Adega</code> é um sistema de gerenciamento de inventário.
  </p>
  <p>
    O seu nome foi inspirado no local onde se armazenam bebidas, especialmente vinhos. Já que a <code>Adega</code> foi desenvolvida originalmente para gerenciar o inventário da <b>Secretaria de TI</b> da
    <a href="https://www.vinhedo.sp.gov.br/">Prefeitura de Vinhedo.</a>
  </p>
  <div class="card bg-body-secondary" style="padding: 1rem; max-width: 15rem;">
    <p class="card-title">
      A <code>Adega</code> ajuda a gerenciar:
      <ul class="card-body">
        <li>Armazéns</li>
        <li>Pessoas</li>
        <li>Empresas</li>
        <li>Categoria de itens</li>
        <li>Itens</li>
      </ul>
    </p>
  </div>
  <h2>Armazéns</h2>
  <p>
    Um <code>armazém</code>, na perspectiva do sistema, é qualquer local onde possam ser gerenciados itens.
  </p>
  <p>
    Ele pode ser um almoxarifado, um depósito, uma sala, um armário, etc.
  </p>
  <p>
    O <code>armazém padrão</code> nada mais é do que aquele que aparecerá por padrão, pré-selecionado, em todos os campos de seleção de <code>armazém</code> do sistema. Ele pode ser alterado a qualquer momento.
  </p>
  <div class="bd-callout bd-callout-warning">
    <strong>Dica: </strong>
    Não é recomendada a criação indiscriminada de armazéns, já que isso pode tornar mais lenta a gestão do inventário. O ideal é criar armazéns apenas para locais que realmente necessitem de controle.
  </div>

  <h2>Pessoas</h2>
  <p>
      Uma <code>pessoa</code> é qualquer indivíduo que precise estar cadastrada no sistema. Ela pode ser uma funcionária, uma colaboradora, uma fornecedora, uma cliente, etc.
  </p>

  <h2>Empresas</h2>
  <p>
      Uma <code>empresa</code> é qualquer entidade que precise estar cadastrada no sistema. Ela pode ser uma empresa, uma instituição, um órgão público, etc.
  </p>

  <h2>Itens & Categoria de Itens</h2>
  <p>
      Um <code>item</code> é qualquer coisa que possa ser gerenciada em um <code>armazém</code>. Ele pode ser um produto, um equipamento, um material, uma licença digital de software, etc. Porém, todo <code>item</code> deve ter uma maneira de ser <strong>unicamente identificado</strong>, seja por um número de série, uma etiqueta patrimonial ou, no limite, o <code>id</code> gerado pelo sistema.
  </p>
  <p>
      Todo <code>item</code> deve ser criado a partir de uma <code>categoria de itens</code>. A <code>categoria de itens</code> é uma abstração que define as características comuns de um grupo de itens.
  <p>
      Por exemplo, <code>a categoria de itens</code> com o nome <strong>"Apple iPhone 16 Pro Max - Titânio Preto"</strong> define perfeitamente um tipo de celular, mas não define um <code>item</code> armazenável. Um <code>item</code> precisa ter sido criado a partir de uma <code>categoria de itens</code> e conter um número exclusivo.
  </p>
  <p>
      Uma <code>categoria de itens</code> não pode ser incluída ou removida de um armazém.
  </p>
  <div class="bd-callout bd-callout-info">
    <strong>Dica: </strong>
    A vantagem de criar uma <code>categoria de itens</code> é que ela permite o cadastro em massa de diversos item no <code>armazém</code>, cada um com seu <strong>id</strong> de sistema. Posteriormente, é possível entrar no <code>armazém</code> e editar detalhes dos <code>itens</code> individualmente sempre que necessário, atribuindo-lhes um número de série, etiqueta patrimonial etc.
  </div>
{% endblock %}

home/templates/home/help_about.html
{% extends 'home/menu.html' %}
{% load static %}
{% block content %}
  <h1>Ajuda</h1>

  <h2>Sobre</h2>
  <p>
    A <code>Adega</code> é um sistema de gerenciamento de inventário.
  </p>
  <p>
    O seu nome foi inspirado no local onde se armazenam bebidas, especialmente vinhos. Já que a <code>Adega</code> foi desenvolvida originalmente para gerenciar o inventário da <b>Secretaria de TI</b> da
    <a href="https://www.vinhedo.sp.gov.br/">Prefeitura de Vinhedo.</a>
  </p>
  <p>
    Além disso a Adega foi desenvolvida para atender as necessidades de uma disciplina chamada <a href="https://apps.univesp.br/o-que-e-projeto-integrador/">Projeto Integrador</a> a do Eixo de Computação da <a href="https://www.univesp.br/">Univesp</a>.
  </p>

  <h2>Quem</h2>
  <p>
    A <code>Adega</code> foi desenvolvida, no backend e front-end, por <strong>Rodrigo Viana Rocha</strong> e teve como gerentes de produto e design os demais colegas da <strong>Univesp 2025, GRUPO-012, PJI110-SALA-004</strong>:
  </p>
  <ul>
    <li>Ana Carolina Ferreira Alves Barcaro</li>
    <li>Andre Wilson Santanna Silva</li>
    <li>Carolina Ferreira Alves</li>
    <li>Daniela Almeida Vieira</li>
    <li>Jean Gustavo da Cunha Marinho</li>
    <li>Leonardo do Valle</li>
    <li>Rodrigo Viana Rocha</li>
    <li>Vanderlei Caetano de Souza</li>
    <li>Zairemylli Francislayne Carreira M Silva</li>
  </ul>
{% endblock %}

home/templates/home/home.html
{% extends 'home/menu.html' %}
{% load static %}
{% block content %}
  <!-- Section  -->
  <h1>Home</h1>
  <h2>Boas-vindas!</h2>
  <p style="font-style: italic;">
    Receba as boas-vindas da Adega,
    <code>
      {% if user.first_name %}
        {{ user.first_name }} {{ user.last_name }}
      {% else %}
        {{ user }}
      {% endif %}
    </code>!
  </p>
  <p>É um prazer ter você de volta conosco.</p>
  <h2>O que vamos fazer hoje?</h2>
  <p>Utilize o menu acima para navegar pelas opções disponíveis. Ele se encontra numa ordem lógica para facilitar o seu uso do sistema:</p>
  <ul>
    <li>Em <strong>Endereços</strong>, você pode inserir, editar e apagar endereços utilizados para Pessoas e Empresas.</li>
    <li>Em <strong>Pessoas</strong>, você pode inserir, editar e apagar tanto Pessoas Físicas, quanto Pessoas Jurídicas.</li>
    <li>Em <strong>Armazéns</strong>, você pode inserir, editar e apagar locais utilizados para armazen.</li>
    <li>Em <strong>Itens</strong>, você pode inserir, editar e apagar tanto Categorias de Itens, quanto Itens Individuais.</li>
    <li>Em <strong>Transações</strong> você pode registrar Entradas e Saídas de Itens em Armazéns.</li>
    <li>Finalmente, em <strong>Relatórios</strong>, você pode gerar relatórios de Estoque por Categorias ou por Itens.</li>
  </ul>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
  <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card shadow bg-body-tertiary p-4" style="min-width: 300px; max-width: 400px;">
      <div class="d-flex justify-content-center align-items-center">
        <img src="{% static 'home/images/three_barrels_light.png' %}" alt="Logo" class="img-fluid" style="width: 80px; height: auto;">
        <h1 style="margin: 0px;">
          Adega
        </h1>
      </div>
      <h3 class="text-center" style="margin-top: 2rem; margin-bottom: 2rem;">Login</h3>
      {% crispy form %}
      {% if messages %}
        {% for message in messages %}
          <!-- success messages-->
          {% if message.tags == 'success' %}
            <div class="alert alert-success" style="margin-top: 1rem;" role="alert">
              {{ message }}
            </div>
          {% endif %}
          <!-- error messages-->
          {% if message.tags == 'error' %}
            <div class="alert alert-danger" style="margin-top: 1rem;" role="alert">
              {{ message }}
            </div>
          {% endif %}
          <!-- warning messages-->
          {% if message.tags == 'warning' %}
            <div class="alert alert-warning" style="margin-top: 1rem;" role="alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock %}

home/templates/home/menu.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
  <nav class="navbar navbar-expand-md shadow fixed-top bg-body-secondary" style="padding: 0rem; margin: 5px;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}" style="padding: 0px;">
          <img src="{% static 'home/images/three_barrels_light.png' %}" alt="Logo" class="img-fluid" style="width: 40px; height: auto;">
          Adega
        </a>
        <!-- Navbar small screens -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar lefthand links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-geo-alt"></i>
              Endereços
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <li>
                <a class="dropdown-item" href="{% url 'address_manager:create_new' %}">
                <i class="bi bi-plus-circle"></i>
                  Incluir
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'address_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-people"></i>
              Pessoas
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <span class="badge bg-secondary text-light" style="margin-left: 0.5rem;">
                <i class="bi bi-building-fill"></i>
                Pessoas Jurídicas
              </span>
              <li>
                <a class="dropdown-item" href="{% url 'company_manager:create_new' %}">
                  <i class="bi bi-plus-circle"></i>
                  Incluir
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'company_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
              </a>
            </li>
              <li><hr class="dropdown-divider"></li>
              <span class="badge bg-secondary text-light" style="margin-left: 0.5rem;">
                <i class="bi bi-people-fill"></i>
                Pessoas Físicas
              </span>
              <li>
                <a class="dropdown-item" href="{% url 'person_manager:create_new' %}">
                  <i class="bi bi-plus-circle"></i>
                  Incluir
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'person_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-archive"></i>
              Armazéns
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <li>
                <a class="dropdown-item" href="{% url 'warehouse_manager:create_new' %}">
                  <i class="bi bi-plus-circle"></i>
                  Incluir
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'warehouse_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-tag"></i>
              Itens
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <span class="badge bg-secondary text-light" style="margin-left: 0.5rem;">
                <i class="bi bi-grid-fill"></i>
                Categorias
              </span>
              <li>
                <a class="dropdown-item" href="{% url 'category_manager:create_new' %}">
                  <i class="bi bi-plus-circle"></i>
                  Incluir
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'category_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <span class="badge bg-secondary text-light" style="margin-left: 0.5rem;">
                <i class="bi bi-tag-fill"></i>
                Itens Individuais
              </span>
              <li>
                <a class="dropdown-item" href="{% url 'item_manager:create_new' %}">
                  <i class="bi bi-plus-circle"></i>
                  Incluir
              </a>
            </li>
              <li>
                <a class="dropdown-item" href="{% url 'item_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-arrow-left-right"></i>
              Transações
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <li>
                <a class="dropdown-item" href="{% url 'transaction_manager:create_new' 'inflow' %}">
                  <i class="bi bi-plus-circle"></i>
                  Entrada</a></li>
              <li>
                <a class="dropdown-item" href="{% url 'transaction_manager:create_new' 'outflow' %}">
                  <i class="bi bi-dash-circle"></i>
                  Saída</a></li>
              <li>
                <a class="dropdown-item" href="{% url 'transaction_manager:list_all' %}">
                  <i class="bi bi-table"></i>
                  Listar/Editar/Apagar
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-file-earmark-text"></i>
              Relatórios
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <li><a class="dropdown-item" href="{% url 'report_manager:list_by' 'category' %}">
                <i class="bi bi-grid"></i>
                Estoque por Categoria
              </a>
            </li>
              <li><a class="dropdown-item" href="{% url 'report_manager:list_by' 'item' %}">
                <i class="bi bi-tag"></i>
                Estoque por Itens
              </a>
            </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-question-circle"></i>
              Ajuda
            </a>
            <ul class="dropdown-menu bg-body-secondary shadow">
              <li>
                <a class="dropdown-item" href="{% url 'home:help_entities' %}">
                  <i class="bi bi-collection"></i>
                  Entidades
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'home:help_examples' %}">
                  <i class="bi bi-play-btn"></i>
                  Exemplos
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'home:help_about' %}">
                  <i class="bi bi-info-circle"></i>
                  Sobre
                </a>
              </li>
            </ul>
          </li>

        </ul>

        <!-- Navbar righthand links -->
        <ul class="navbar-nav mb-2" style="align-items: center;">
            <li class="nav-item dropdown">
            <a class="nav-link d-flex align-items-center" style="padding: 0px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle" style="color: #0AF; font-size: 1.5rem;"></i>
                {% if user.is_superuser %}
                <i class="bi bi-shield-lock" style="color: #F60; font-size: 1rem; position: relative; top: 0.5rem;"></i>
              {% endif %}
              <span class="ms-2">{{ user.username }}</span>
            </a>

            <ul class="dropdown-menu dropdown-menu-end bg-body-secondary">
              <li>
                <a class="dropdown-item" href="{% url 'home:change_password' %}">
                    <i class="bi bi-key"></i>
                    Alterar senha
              </a>
            </li>
              {% if user.is_superuser %}
                <li><hr class="dropdown-divider"></li>
                <li>
                  <a class="dropdown-item" href="{% url 'admin:index' %}">
                    <i class="bi bi-gear" style="color: #F60"></i>
                    Gerenciar Sistema
                  </a>
                </li>
              {% endif %}
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item" href="{% url 'home:hlogout' %}">
                  <i class="bi bi-door-closed"></i>
                  Fazer logout
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Main content -->
  <div class="container" style="margin-top: 6rem;">
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}