address_manager/urls.py
from . import views
from django.urls import path, include


app_name = views.APP_STR
urlpatterns = [
    path('create/', views.create_new, name='create_new'),
    path('delete/', views.delete_bulk, name='delete_bulk'),
    path('edit/<int:id>/', views.edit_id, name='edit_id'),
    path('list/', views.list_all, name='list_all'),
    path('list_all_api/', views.list_all_api, name='list_all_api'),
    path('view/<int:id>/', views.view_id, name='view_id'),
]

adega/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path(
        'address_manager/',
        include('address_manager.urls'),
        name='address_manager'
    ),
    path(
        'company_manager/',
        include('company_manager.urls'),
        name='company_manager'
    ),
    path(
        'person_manager/',
        include('person_manager.urls'),
        name='person_manager'
    ),
    path(
        'category_manager/',
        include('category_manager.urls'),
        name='category_manager'
    ),
    path(
        'warehouse_manager/',
        include('warehouse_manager.urls'),
        name='warehouse_manager'
    ),
    path(
        'item_manager/',
        include('item_manager.urls'),
        name='item_manager'
    ),
    path(
        'transaction_manager/',
        include('transaction_manager.urls'),
        name='transaction_manager'
    ),
    path(
        'report_manager/',
        include('report_manager.urls'),
        name='report_manager'
    ),

    path("select2/", include("django_select2.urls")),
]

home/urls.py
from . import views
from django.urls import path, include


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('help/about/', views.help_about, name='help_about'),
    path('help/entities/', views.help_entities, name='help_entities'),
    path('help/examples/', views.help_examples, name='help_examples'),
    path('login/', views.hlogin, name='hlogin'),
    path('logout/', views.hlogout, name='hlogout'),
    path(
        'change_password/',
        views.change_password,
        name='change_password'
    ),
]

address_manager/models.py
from django.db import models


class Address(models.Model):
    verbose_name = "Endereço"
    zip_code = models.CharField(
        "CEP",
        max_length=16,
    )

    street = models.CharField(
        "Logradouro",
        max_length=64,
    )

    number = models.CharField(
        "Número",
        max_length=8,
        blank=True,
    )

    complement = models.CharField(
        "Complemento",
        max_length=32,
        blank=True,
    )

    neighborhood = models.CharField(
        "Bairro",
        max_length=64,
    )

    city = models.CharField(
        "Cidade",
        max_length=64,
    )

    state = models.CharField(
        "Estado",
        max_length=64,
    )

    country = models.CharField(
        "País",
        max_length=64,
        default="Brasil",
    )

    reference = models.TextField(
        "Referência",
        blank=True,
    )

    created_at = models.DateTimeField(
        "Criado em",
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        "Atualizado em",
        auto_now=True,
    )

    def __str__(self):
        summary = (
            f"{self.street}, {self.number + ', ' if self.number else ''}"
            f"{self.complement + ', ' if self.complement else ''}"
            f"{self.city}/{self.state}, {self.country}"
        )
        return summary


    class Meta:
        verbose_name = "Endereço"
        verbose_name_plural = "Endereços"
        ordering = ["zip_code", "street", "number"]
        indexes = [
            models.Index(fields=["zip_code"]),
        ]

address_manager/forms.py
from django import forms
from django.apps import apps
from django.db.models import Model
from django_select2.forms import ModelSelect2Widget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder, Button, Submit

## Make changes here -------------------------------------------------------
APP_STR = "address_manager"
MODEL_STR = "Address"
VIEW_ROUTE = f"/{APP_STR}/list/"
# Define all the widgets for foreign key fields
class AddressWidget(ModelSelect2Widget):
    queryset = apps.get_model('address_manager', 'Address').objects.all()
    search_fields = [
        'zip_code__icontains',
        'street__icontains',
        'number__icontains',
        'complement__icontains',
        'neighborhood__icontains',
        'city__icontains',
        'state__icontains',
        'country__icontains',
    ]
## -------------------------------------------------------------------------

try:
    MODEL: Model = apps.get_model(APP_STR, MODEL_STR)
except ImportError:
    MODEL: Model = None
    raise ImportError(
        f"Model {MODEL_STR} not found in app {APP_STR}. "
        f"Please check the model name and app name."
    )

class CrudForm(forms.ModelForm):
    class Meta:
        model = MODEL
        fields = "__all__"
        # Assign the custom widget to the 'address' field
        widgets = {
            'address': AddressWidget,
        }

    def __init__(self, *args, crud_form_type="create" ,**kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_method = "POST"

        # Add buttons based on crud_form_type (Your existing logic)
        if crud_form_type == "create":
            self.helper.layout.append(
                ButtonHolder(
                    Submit(
                        "submit",
                        "Incluir",
                        css_class="btn btn-primary"),
                    Button("cancel",
                           "Cancelar",
                           css_class="btn btn-secondary",
                           onclick=f"window.location.href='{VIEW_ROUTE}'"),
                           css_class=("d-grid gap-2 d-md-flex "
                            "justify-content-end"),
                )
            )
        elif crud_form_type == "edit":
             self.helper.layout.append(
                 ButtonHolder(
                     Submit(
                         "submit",
                         "Salvar",
                         css_class="btn btn-primary"),
                     Button("cancel",
                            "Cancelar",
                            css_class="btn btn-secondary",
                            onclick=f"window.location.href='{VIEW_ROUTE}'"),
                           css_class=("d-grid gap-2 d-md-flex "
                            "justify-content-end"),
                 )
             )
        elif crud_form_type == "view":
            for field_name in self.fields:
                self.fields[field_name].disabled = True
                self.fields[field_name].widget.attrs.update(
                    {"readonly": "readonly"})

            self.helper.layout.append(
                ButtonHolder(
                    Button("edit",
                           "Voltar",
                           css_class="btn btn-primary",
                           onclick=f"window.location.href='{VIEW_ROUTE}'"),
                           css_class=("d-grid gap-2 d-md-flex "
                            "justify-content-end"),
                )
            )

address_manager/views.py
from .forms import CrudForm
from django.apps import apps
from django.contrib import messages
from django.db import transaction
from django.db.models import ForeignKey, Model, Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse


## Make changes here -------------------------------------------------------
APP_STR = "address_manager"
MODEL_STR = "Address"
TABLE_COLUMNS = {
    # can't have relationships columns
    0: 'id', # this is mandatory (don't remove)
    1: 'zip_code',
    2: 'street',
    3: 'number',
    4: 'complement',
    5: 'neighborhood',
    6: 'city',
    7: 'state',
    8: 'country',
}
## -------------------------------------------------------------------------


# Dynamic import of a class model described by MODEL_STR
try:
    MODEL: Model = apps.get_model(APP_STR, MODEL_STR)
except ImportError:
    MODEL: Model = None
    raise ImportError(
        f"Model {MODEL_STR} not found in app {APP_STR}. "
        f"Please check the model name and app name."
    )

FK_FIELDS = [
    field.name for field in MODEL._meta.get_fields()
    if isinstance(field, ForeignKey)
]
VERBOSE_COLUMN_LIST = []
for field in TABLE_COLUMNS.values():
    VERBOSE_COLUMN_LIST.append(
        MODEL._meta.get_field(field).verbose_name
    )
VERBOSE_NAME = MODEL._meta.verbose_name
VERBOSE_NAME_PLURAL = MODEL._meta.verbose_name_plural

def get_match_in_any_column_query(search_value):
    """
    Creates a query object that matches the search_value in any of the fields
    defined in TABLE_COLUMNS, including foreign key fields.
    """
    query = Q()
    for field in TABLE_COLUMNS.values():
        if field in FK_FIELDS:
            # Assuming we want to search on the primary key of the related model
            query = query | Q(**{f"{field}__pk__icontains": search_value})
        else:
            query = query | Q(**{f"{field}__icontains": search_value})
    return query

def create_new(request):
    ACTION = "Incluir " + VERBOSE_NAME
    if request.method == "POST":
        form = CrudForm(request.POST, crud_form_type="create")
        if form.is_valid():
            form.save()
            messages.success(
                request,
                VERBOSE_NAME + " anterior criado(a) com sucesso."
            )
            # clear the form
            form = CrudForm(crud_form_type="create")
        else:
            messages.error(
                request,
                VERBOSE_NAME + " anterior não foi criado(a)."
            )
            # return the form with errors
    else:
        form = CrudForm(crud_form_type="create")
    return render(
        request,
        APP_STR + "/create_edit_view.html",
        {'form': form, 'action': ACTION},
    )

def delete_bulk(request):
    ACTION = "Apagar " + VERBOSE_NAME
    # Get the entity object by id
    if request.method == "POST":
        # delete all related ids in a single atomic bulk transaction
        ids = request.POST.getlist('selected_rows[]')
        with transaction.atomic():
            MODEL.objects.filter(id__in=ids).delete()
    return redirect(reverse(f"{APP_STR}:list_all"))

def edit_id(request, id):
    ACTION = "Editar " + VERBOSE_NAME
    # Get the address object by id
    entity = MODEL.objects.get(id=id)
    # Create the form with the address object
    if request.method == "POST":
        form = CrudForm(request.POST, instance=entity, crud_form_type="edit")
        if form.is_valid():
            form.save()
            return redirect(reverse(f"{APP_STR}:list_all"))
    else:
        form = CrudForm(instance=entity, crud_form_type="edit")
    return render(
        request, APP_STR + "/create_edit_view.html",
        {'form': form, 'action': ACTION},
    )

def list_all(request):
    ACTION = "Listar/Editar/Apagar " + VERBOSE_NAME_PLURAL
    return render(
        request,
        APP_STR + "/list.html",
        {'action': ACTION, 'table_columns': VERBOSE_COLUMN_LIST,},
    )

def list_all_api(request):
    # Get DataTables parameters
    draw = int(request.GET.get('draw', 0))
    start = int(request.GET.get('start', 0))
    length = int(request.GET.get('length', 10))
    search_value = request.GET.get('search[value]', '')
    order_column_index = int(request.GET.get('order[0][column]', 0))
    order_dir = request.GET.get('order[0][dir]', 'asc')

    # Get the field name from mapping,
    # default to 'id' if index is out of bounds
    order_column_name = TABLE_COLUMNS.get(order_column_index, 'id')
    if order_dir == 'desc':
        order_column_name = f"-{order_column_name}"

    # Base QuerySet
    queryset = MODEL.objects.all()

    # Total records count before filtering
    records_total = queryset.count()

    # Filter records based on search value, matching any column
    if search_value:
        queryset = queryset.filter(
            get_match_in_any_column_query(search_value)
        )
    records_filtered = queryset.count()

    # Apply sorting and pagination
    queryset = (
        queryset.order_by(order_column_name).distinct()[start:start + length]
    )

    # Prepare data field for JSON response to DataTables
    data = []
    for qs in queryset:
        row = []
        for col in TABLE_COLUMNS.values():
            if col in FK_FIELDS:
                # Serialize foreign key fields
                # (e.g., use their string representation or a specific field)
                fk_instance = getattr(qs, col)
                col_value = str(fk_instance) if fk_instance else None
            else:
                # Serialize regular fields
                col_value = getattr(qs, col, None)
            row.append(col_value)
        data.append(row)

    # Format JSON Response to DataTables request
    response = {
        'draw': draw,
        'recordsTotal': records_total,
        'recordsFiltered': records_filtered,
        'data': data,
    }
    return JsonResponse(response)

def view_id(request, id):
    ACTION = "Visualizar detalhes de " + VERBOSE_NAME
    # Get the entity object by id
    entity = MODEL.objects.get(id=id)

    # Create the form with the entity object
    form = CrudForm(instance=entity, crud_form_type="view")
    return render(
        request,
        APP_STR +"/create_edit_view.html",
        {'form': form, 'action': ACTION},
    )

address_manager/templates/address_manager/create_edit_view.html
{% extends "home/menu.html" %}
{% block content %}
  <div class="container d-flex justify-content-center">
    <div class="card bg-body-tertiary shadow" style="width: 36rem;">
      <div class="container" style="padding: 2rem;">
        {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div class="alert alert-success mt-3" role="alert">
              <b>Sucesso: </b>{{ message }}
            </div>
          {% endif %}
          {% if message.tags == 'error' %}
            <div class="alert alert-danger mt-3" role="alert">
              <b>Erro: </b>{{ message }}
            </div>
          {% endif %}
          {% endfor %}
        {% endif %}
      <h3 style="margin-bottom: 2rem;">{{ action }}</h3>
      <form method="post" novalidate>
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {% crispy form %}
      </form>
    </div>
    </div>
  </div>
<script>
  $(document).ready(function () {
    $('#id_zip_code').focus();
    // In case escape key is pressed, exit the form and go to the list page
    $(document).on('keydown', function (e) {
      if (e.key === 'Escape') {
        window.location.href = '/address_manager/list/';
      }
    });
    // Search for address using zip code
    $('#id_zip_code').on('focusout', function () {
      const zipCode = $(this).val().replace(/\D/g, '');
      if (zipCode) {
        const url = "https://brasilapi.com.br/api/cep/v2/"+zipCode;
        $.ajax({
          url: url,
          method: 'GET',
          dataType: 'json',
          success: function (data) {
            // update input fields with the data received
            $('#id_street').val(data.street || '');
            $('#id_neighborhood').val(data.neighborhood || '');
            $('#id_city').val(data.city || '');
            $('#id_state').val(data.state || '');
            // Set the focus on the street field
            $('#id_number').focus();
            // error messsage if zip code is not found, but service is ok
            if (data.errors) {
              alert('Erro: ' + data.errors[0].message);
            }
          },
        });
      }
    });
  });
</script>
{% endblock %}

address_manager/templates/address_manager/create_view.html
{% extends "home/menu.html" %}
{% block content %}
  <div class="container d-flex justify-content-center">
    <div class="card bg-body-tertiary shadow" style="margin-top: 2rem; margin-bottom: 2rem; width: 36rem;">
      <div class="container" style="padding: 2rem;">
        {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div class="alert alert-success mt-3" role="alert">
              <b>Sucesso: </b>{{ message }}
            </div>
          {% endif %}
          {% if message.tags == 'error' %}
            <div class="alert alert-danger mt-3" role="alert">
              <b>Erro: </b>{{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      <h3 style="margin-bottom: 2rem;">{{ action }}</h3>
      <form method="post" novalidate>
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
    </div>
  </div>
{% endblock %}

address_manager/templates/address_manager/list.html
{% extends "home/menu.html" %}
{% block content %}
  <div class="card bg-body-tertiary shadow" style="padding: 1rem;">
    <h3 style="margin-bottom: 2rem;">{{ action }}</h3>
    <p>Selecione um (ou mais) registros na tabela abaixo e clique em um dos botões para executar a ação.</p>
    <table id="data-table" class="table table-striped" style=" width:100%">
      <thead>
        <tr>
          {%for column in table_columns %}
            <th>{{ column }}</th>
          {% endfor %}
        </tr>
      </thead>
    </table>
    <div class="d-grid gap-2 d-md-flex justify-content-end" style="margin-top: 2rem;">
      <button id="create_button" class="btn btn-primary">Incluir</button>
      <button id="view_button" class="btn btn-primary">Detalhes</button>
      <button id="edit_button" class="btn btn-primary">Editar</button>
      <button id="delete_button" class="btn btn-danger">Apagar</button>
    </div>
  </div>
  <script>
    $(document).ready(function () {
      //- Change here --------------------------------------------------------
      const create_new_url = '{% url "address_manager:create_new" %}';
      const delete_bulk_url = '{% url "address_manager:delete_bulk" %}';
      const edit_id_url = '/address_manager/edit/';
      const list_all_api_url = '{% url "address_manager:list_all_api" %}';
      const view_id_url = '/address_manager/view/';
      //----------------------------------------------------------------------

      //----------------------------------------------------------------------
      // DataTables setup
      //----------------------------------------------------------------------
      const table = new DataTable('#data-table', {
        ajax: list_all_api_url,
        language: {
          url: 'https://cdn.datatables.net/plug-ins/2.2.2/i18n/pt-BR.json',
        },
        processing: true, // show loading indicator
        serverSide: true,
        pageLength: 5,
        lengthMenu: [5, 10, 25, 50, 100],
        select: {
          style: 'multi',
        },
      });

      //----------------------------------------------------------------------
      // Function to visually update View and Edit buttons according to the
      // selected rows, on select and deselect events
      //----------------------------------------------------------------------
      function updateButtons() {
        if (selectedRowsIds.length === 0) {
          $ ( "#view_button" ).prop('disabled', true);
          $ ( "#edit_button" ).prop('disabled', true);
          $ ( "#delete_button" ).prop('disabled', true);
        }
        if (selectedRowsIds.length === 1) {
          $ ( "#view_button" ).prop('disabled', false);
          $ ( "#edit_button" ).prop('disabled', false);
          $ ( "#delete_button" ).prop('disabled', false);
        }
        if (selectedRowsIds.length > 1) {
          $ ( "#view_button" ).prop('disabled', true);
          $ ( "#edit_button" ).prop('disabled', true);
          $ ( "#delete_button" ).prop('disabled', false);
        }
      }

      //----------------------------------------------------------------------
      // Update the selectRowsIds array on select and deselect events
      //----------------------------------------------------------------------
      var selectedRowsIds = [];
      updateButtons();
      // Handle row selection in DataTable object table
      table.on('select', function(e, dt, type, indexes) {
        if (type === 'row') {
          var rowData = table.rows(indexes).data().toArray();
          if (rowData.length > 0 && rowData[0].length > 0) {
            // Get the content of the first cell (index 0 = id)
            // of the first selected row
            var firstCellContent = rowData[0][0];
            // if the first cell content is not already in
            // the selectedRowsIds array, add it
            if (!selectedRowsIds.includes(firstCellContent)) {
              selectedRowsIds.push(firstCellContent);
            }
            updateButtons();
          }
        }
      });
      // Handle row deselection in DataTable object table
      table.on('deselect', function(e, dt, type, indexes) {
        if (type === 'row') {
          var rowData = table.rows(indexes).data().toArray();
          if (rowData.length > 0 && rowData[0].length > 0) {
            // Get the content of the first cell (index 0) of the
            // first selected row
            var firstCellContent = rowData[0][0];
            // if the first cell content is in the selectedRowsIds array,
            //  remove it
            if (selectedRowsIds.includes(firstCellContent)) {
              selectedRowsIds = selectedRowsIds.filter(function(item) {
                return item !== firstCellContent;
              });
              updateButtons();
            }
          }
        }
      });

      //----------------------------------------------------------------------
      // Button click event handlers when the buttons are enabled
      //----------------------------------------------------------------------
      $( '#create_button' ).click(function() {
          window.location.href = create_new_url;
      });
      $( '#view_button' ).click(function() {
        if (!$(this).prop('disabled')) {
          window.location.href = view_id_url + selectedRowsIds[0] + '/';
        }
      });
      $( '#edit_button' ).click(function() {
        if (!$(this).prop('disabled')) {
          window.location.href = edit_id_url + selectedRowsIds[0] + '/';
        }
      });
      $( '#delete_button' ).click(function() {
        // Show confirmation dialog before deletion
        // it shows the total number of selected rows and their IDs
        if (selectedRowsIds.length > 1) {
          var isConfirmationOk = confirm(
            'Você tem certeza que deseja apagar ' + selectedRowsIds.length +
            ' registros?\n' +
            '- Escolhidos: ' + selectedRowsIds.join(', ') + '\n' +
            '- CUIDADO: registros dependentes a eles também serão apagados!'
          );
        } else {
          var isConfirmationOk = confirm(
            'Você tem certeza que deseja apagar o registro ' +
            selectedRowsIds[0] + '?\n' +
            '- CUIDADO: registros dependentes a ele também serão apagados!'
          );
        }
        if (!$(this).prop('disabled') && isConfirmationOk) {
          // Send a POST request to the delete URL with the selected row IDs
          $.ajax({
            url: delete_bulk_url,
            type: 'POST',
            data: {
              'selected_rows': selectedRowsIds,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
              // Reload the table after successful deletion
              table.ajax.reload();
              selectedRowsIds = [];
              updateButtons();
            },
            error: function(xhr, status, error) {
              console.error('Error deleting rows:', error);
            }
          });
        }
      });
    });
  </script>
{% endblock %}